spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/gestikulatordb
    username: postgres
    password: bazepodataka
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-1.0.xml
    user: postgres
    password: bazepodataka
    url: jdbc:postgresql://localhost:5433/gestikulatordb
