spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/gestikulatordb
    username: postgres
    password: bazepodataka
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.xml
    user: postgres
    password: bazepodataka

  liquibase.drop-first: true

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
